Updated hacked FAQ page and dependencies
defientco/Everything-Corp-UI pull request #33
Opened 2023-04-13 22:11 UTC by edkeziah

This pull request implements a hacked version of the FAQ page. Please review the changes and let me know if there are any issues or concerns.

2023-04-19 21:15 UTC, SweetmanTech commented on .gitignore
> +.yarn
nice addition 🔥

2023-04-19 21:15 UTC, SweetmanTech commented on .yarnrc.yml
> +nodeLinker: node-modules
what's the purpose of this change?

Is this file needed? Or, was it an accidental addition?

2023-04-19 21:15 UTC, SweetmanTech commented on pages/faq/index.tsx
> +    {/* Add the hacked images */}
remove comments.

philosophy: code should be self-documenting

2023-04-19 21:15 UTC, SweetmanTech commented on pages/faq/index.tsx
> +    {/* Add the hacked images */}
```suggestion
```

2023-04-19 21:15 UTC, SweetmanTech commented on pages/faq/index.tsx
> +    </div>
this is fine for now, however, I think best-practice here is to abstract this code to a new component.

I'd call it `<HackedFaqOverlay />`

philosophy: [A module should be responsible to one, and only one, actor.](https://en.wikipedia.org/wiki/Single-responsibility_principle)

2023-04-19 21:21 UTC, SweetmanTech requested changes
`package.json` needs to have merge conflicts resolved

2023-04-19 21:21 UTC, SweetmanTech commented on package.json
> +>>>>>>> a3ad70eadab0bf34424d4581ff83e50e161ebf4f
you need to resolve the merge conflicts.

2023-04-19 21:32 UTC, edkeziah commented on .yarnrc.yml
> +nodeLinker: node-modules
I added the `nodeLinker: node-modules` setting to the `.yarnrc.yml` file, but I don't remember the specific reason for doing so. I've reviewed the codebase history and documentation, but I couldn't find any information that would provide me with the necessary context.

Could you please help me understand why this setting was added? I want to make sure that my changes are in line with the team's standards and practices.

Thanks in advance for your help!

2023-04-19 21:58 UTC, crazzywizard commented on .yarnrc.yml
> +nodeLinker: node-modules
This was done as an attempt to figure out why `yarn install` was creating .yarn folder and fix it.

2023-04-24 10:26 UTC, SweetmanTech approved these changes

2023-04-24 10:30 UTC, merged